//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGuides.Domain {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DomainEntitiesValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainEntitiesValidationMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyGuides.Domain.DomainEntitiesValidationMessages", typeof(DomainEntitiesValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tamanho máximo do campo descrição é de {0} carácteres..
        /// </summary>
        internal static string AchievementValidator_Description_MaxLength {
            get {
                return ResourceManager.GetString("AchievementValidator_Description_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo descrição da conquista não pode estar nulo..
        /// </summary>
        internal static string AchievementValidator_Description_Required {
            get {
                return ResourceManager.GetString("AchievementValidator_Description_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar a qual jogo a conquista pertence..
        /// </summary>
        internal static string AchievementValidator_GameId_Required {
            get {
                return ResourceManager.GetString("AchievementValidator_GameId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar se a conquista está oculta..
        /// </summary>
        internal static string AchievementValidator_Hidden_Required {
            get {
                return ResourceManager.GetString("AchievementValidator_Hidden_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tamanho máximo do campo imagem da conquista é de {0} carácteres..
        /// </summary>
        internal static string AchievementValidator_Icon_MaxLength {
            get {
                return ResourceManager.GetString("AchievementValidator_Icon_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo imagem da conquista é obrigatório..
        /// </summary>
        internal static string AchievementValidator_Icon_Required {
            get {
                return ResourceManager.GetString("AchievementValidator_Icon_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tamanho máximo do campo imagem da conquista bloqueada é de {0} carácteres..
        /// </summary>
        internal static string AchievementValidator_IconGray_MaxLength {
            get {
                return ResourceManager.GetString("AchievementValidator_IconGray_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo imagem da conquista bloqueada é obrigatório..
        /// </summary>
        internal static string AchievementValidator_IconGray_Required {
            get {
                return ResourceManager.GetString("AchievementValidator_IconGray_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tamanho máximo do cmapo nome da conquista é de {0} carácteres..
        /// </summary>
        internal static string AchievementValidator_Name_MaxLength {
            get {
                return ResourceManager.GetString("AchievementValidator_Name_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo nome da conquista é obrigatório..
        /// </summary>
        internal static string AchievementValidator_Name_Required {
            get {
                return ResourceManager.GetString("AchievementValidator_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar se o tipo do banner está oculto..
        /// </summary>
        internal static string BannerTypeValidator_Hidden_Required {
            get {
                return ResourceManager.GetString("BannerTypeValidator_Hidden_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tamanho máximo do campo nome do tipo de banner é de {0} carácteres..
        /// </summary>
        internal static string BannerTypeValidator_Name_MaxLength {
            get {
                return ResourceManager.GetString("BannerTypeValidator_Name_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo nome do tipo do banner é obrigatório..
        /// </summary>
        internal static string BannerTypeValidator_Name_Required {
            get {
                return ResourceManager.GetString("BannerTypeValidator_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo id do tipo de banner é obrigatório..
        /// </summary>
        internal static string BannerValidator_BannerTypeId_Required {
            get {
                return ResourceManager.GetString("BannerValidator_BannerTypeId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tamanho máximo do campo imagem é de {0} carácteres..
        /// </summary>
        internal static string BannerValidator_ImageId_MaxLength {
            get {
                return ResourceManager.GetString("BannerValidator_ImageId_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo imagem do banner é obrigatório..
        /// </summary>
        internal static string BannerValidator_ImageId_Required {
            get {
                return ResourceManager.GetString("BannerValidator_ImageId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tamanho máximo do campo nome é de {0} carácteres..
        /// </summary>
        internal static string BannerValidator_Name_MaxLength {
            get {
                return ResourceManager.GetString("BannerValidator_Name_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo nome do banner é obrigatório..
        /// </summary>
        internal static string BannerValidator_Name_Required {
            get {
                return ResourceManager.GetString("BannerValidator_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tamanho máximo do campo url é de {0} carácteres..
        /// </summary>
        internal static string BannerValidator_Url_MaxLength {
            get {
                return ResourceManager.GetString("BannerValidator_Url_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo url do banner é obrigatório..
        /// </summary>
        internal static string BannerValidator_Url_Required {
            get {
                return ResourceManager.GetString("BannerValidator_Url_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tamanho máximo do campo imagem da dificuldade é de {0} carácteres..
        /// </summary>
        internal static string DifficultyValidator_Image_MaxLength {
            get {
                return ResourceManager.GetString("DifficultyValidator_Image_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo imagem da dificuldade é obrigatório..
        /// </summary>
        internal static string DifficultyValidator_Image_Required {
            get {
                return ResourceManager.GetString("DifficultyValidator_Image_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tamanho máximo do campo nome da dificuldade é de {0} carácteres..
        /// </summary>
        internal static string DifficultyValidator_Name_MaxLength {
            get {
                return ResourceManager.GetString("DifficultyValidator_Name_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo nome da dificuldade é obrigatório..
        /// </summary>
        internal static string DifficultyValidator_Name_Required {
            get {
                return ResourceManager.GetString("DifficultyValidator_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo ordem da dificuldade é obrigatório..
        /// </summary>
        internal static string DifficultyValidator_Order_Required {
            get {
                return ResourceManager.GetString("DifficultyValidator_Order_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo app id do jogo é obrigatório..
        /// </summary>
        internal static string GameValidator_AppId_Required {
            get {
                return ResourceManager.GetString("GameValidator_AppId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tamanho máximo do campo nome do jogo é de {0} carácteres..
        /// </summary>
        internal static string GameValidator_Name_MaxLength {
            get {
                return ResourceManager.GetString("GameValidator_Name_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo nome do jogo é obrigatório..
        /// </summary>
        internal static string GameValidator_Name_Required {
            get {
                return ResourceManager.GetString("GameValidator_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo versão do jogo é obrigatório..
        /// </summary>
        internal static string GameValidator_Version_Required {
            get {
                return ResourceManager.GetString("GameValidator_Version_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo conteúdo da seção é obrigatório..
        /// </summary>
        internal static string SectionValidator_Content_Required {
            get {
                return ResourceManager.GetString("SectionValidator_Content_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo individual é obrigatório..
        /// </summary>
        internal static string SectionValidator_IsIndividual_Required {
            get {
                return ResourceManager.GetString("SectionValidator_IsIndividual_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tamanho máximo do campo nome de seção é de {0} caráceteres..
        /// </summary>
        internal static string SectionValidator_Name_MaxLength {
            get {
                return ResourceManager.GetString("SectionValidator_Name_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo nome da seção é obrigatório..
        /// </summary>
        internal static string SectionValidator_Name_Required {
            get {
                return ResourceManager.GetString("SectionValidator_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo email está inválido.
        /// </summary>
        internal static string UserValidator_Email_Invalid {
            get {
                return ResourceManager.GetString("UserValidator_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo email é obrigatório.
        /// </summary>
        internal static string UserValidator_Email_Required {
            get {
                return ResourceManager.GetString("UserValidator_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo senha é obrigatório.
        /// </summary>
        internal static string UserValidator_Password_Required {
            get {
                return ResourceManager.GetString("UserValidator_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo usuário é obrigatório.
        /// </summary>
        internal static string UserValidator_Username_Required {
            get {
                return ResourceManager.GetString("UserValidator_Username_Required", resourceCulture);
            }
        }
    }
}
