//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGuides.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DomainEntitiesValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainEntitiesValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyGuides.Domain.DomainEntitiesValidationMessages", typeof(DomainEntitiesValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário informar se o tipo do banner está oculto..
        /// </summary>
        internal static string BannerTypeValidator_Hidden_Required {
            get {
                return ResourceManager.GetString("BannerTypeValidator_Hidden_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho máximo do campo nome do tipo de banner é de {0} carácteres..
        /// </summary>
        internal static string BannerTypeValidator_Name_MaxLength {
            get {
                return ResourceManager.GetString("BannerTypeValidator_Name_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome do tipo do banner é obrigatório..
        /// </summary>
        internal static string BannerTypeValidator_Name_Required {
            get {
                return ResourceManager.GetString("BannerTypeValidator_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo id do tipo de banner é obrigatório..
        /// </summary>
        internal static string BannerValidator_BannerTypeId_Required {
            get {
                return ResourceManager.GetString("BannerValidator_BannerTypeId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho máximo do campo imagem é de {0} carácteres..
        /// </summary>
        internal static string BannerValidator_ImageId_MaxLength {
            get {
                return ResourceManager.GetString("BannerValidator_ImageId_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo imagem do banner é obrigatório..
        /// </summary>
        internal static string BannerValidator_ImageId_Required {
            get {
                return ResourceManager.GetString("BannerValidator_ImageId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho máximo do campo nome é de {0} carácteres..
        /// </summary>
        internal static string BannerValidator_Name_MaxLength {
            get {
                return ResourceManager.GetString("BannerValidator_Name_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome do banner é obrigatório..
        /// </summary>
        internal static string BannerValidator_Name_Required {
            get {
                return ResourceManager.GetString("BannerValidator_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho máximo do campo url é de {0} carácteres..
        /// </summary>
        internal static string BannerValidator_Url_MaxLength {
            get {
                return ResourceManager.GetString("BannerValidator_Url_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo url do banner é obrigatório..
        /// </summary>
        internal static string BannerValidator_Url_Required {
            get {
                return ResourceManager.GetString("BannerValidator_Url_Required", resourceCulture);
            }
        }
    }
}
